# Computational Astrophysics
## 04. Fundamentals of Python. Reading and Writing Files

---
## Eduard Larrañaga

Observatorio Astronómico Nacional\
Facultad de Ciencias\
Universidad Nacional de Colombia

---

### About this notebook

In this notebook we present some of the fundamentals of `python` coding.

---

### Reading Files

#### Simple reading of a file
Open the file, read the data and close the file (to prevent file corruption)

In [1]:
infile = open('example_file1.txt','r')
data = infile.readlines()
infile.close()

The data was readed line by line and is stored in an array:

In [2]:
data

['Beta (v/c)\t Gamma \n',
 '0\t\t 1 \n',
 '0.0001\t\t 1 \n',
 '0.0002\t\t 1 \n',
 '0.0003\t\t 1 \n',
 '0.0004\t\t 1 \n',
 '0.0005\t\t 1 \n',
 '0.0006\t\t 1 \n',
 '0.0007\t\t 1 \n',
 '0.0008\t\t 1 \n',
 '0.0009\t\t 1 \n',
 '0.001\t\t 1 \n',
 '0.0011\t\t 1 \n',
 '0.0012\t\t 1 \n',
 '0.0013\t\t 1 \n',
 '0.0014\t\t 1 \n',
 '0.0015\t\t 1 \n',
 '0.0016\t\t 1 \n',
 '0.0017\t\t 1 \n',
 '0.0018\t\t 1 \n',
 '0.0019\t\t 1 \n',
 '0.002\t\t 1 \n',
 '0.0021\t\t 1 \n',
 '0.0022\t\t 1 \n',
 '0.0023\t\t 1 \n',
 '0.0024\t\t 1 \n',
 '0.0025\t\t 1 \n',
 '0.0026\t\t 1 \n',
 '0.0027\t\t 1 \n',
 '0.0028\t\t 1 \n',
 '0.0029\t\t 1 \n',
 '0.003\t\t 1 \n',
 '0.0031\t\t 1 \n',
 '0.0032\t\t 1.00001 \n',
 '0.0033\t\t 1.00001 \n',
 '0.0034\t\t 1.00001 \n',
 '0.0035\t\t 1.00001 \n',
 '0.0036\t\t 1.00001 \n',
 '0.0037\t\t 1.00001 \n',
 '0.0038\t\t 1.00001 \n',
 '0.0039\t\t 1.00001 \n',
 '0.004\t\t 1.00001 \n',
 '0.0041\t\t 1.00001 \n',
 '0.0042\t\t 1.00001 \n',
 '0.0043\t\t 1.00001 \n',
 '0.0044\t\t 1.00001 \n',
 '0.0

#### Reading file and storing information in arrays
First we read the data from the file:

In [3]:
import numpy as np

infile = open('example_file2.txt','r')
indata = infile.readlines()
infile.close()
indata

['# Text Description\n',
 '0.0000000000E+00,0.0000000000E+00\n',
 '1.8868424346E-02,1.8867094876E-02 \n',
 '3.7736848692E-02,3.7726213718E-02\n',
 '5.6605273038E-02,5.6569384424E-02\n',
 '7.5473697384E-02,7.5388642756E-02 \n',
 '9.4342121729E-02,9.4176036262E-02 \n',
 '1.1321054608E-01,1.1292362820E-01 \n',
 '1.3207897042E-01,1.3162350145E-01']

Now, we create the empty numpy arrays:

In [4]:
n = len(indata) - 1
time = np.zeros(n)
data = np.zeros(n)

We parse the data (which is separated by commas in the file)

In [5]:
for i in range(n):
    splitline = indata[i+1][:-1].split(',')
    time[i] = float(splitline[0])
    data[i] = float(splitline[1])

In [6]:
time

array([0.        , 0.01886842, 0.03773685, 0.05660527, 0.0754737 ,
       0.09434212, 0.11321055, 0.13207897])

In [7]:
data

array([0.        , 0.01886709, 0.03772621, 0.05656938, 0.07538864,
       0.09417604, 0.11292363, 1.31623501])

#### Using `numpy` to directly loading the data 
Using `numpy`, it is possible to store the data in a numpy array directly from the file. 

In [8]:
import numpy as np

data = np.loadtxt('example_file3.txt', comments='#')
data

array([[0.        , 0.        ],
       [0.01886842, 0.01886709],
       [0.03773685, 0.03772621],
       [0.05660527, 0.05656938],
       [0.0754737 , 0.07538864],
       [0.09434212, 0.09417604],
       [0.11321055, 0.11292363],
       [0.13207897, 0.1316235 ]])

In [9]:
data[:,0]

array([0.        , 0.01886842, 0.03773685, 0.05660527, 0.0754737 ,
       0.09434212, 0.11321055, 0.13207897])

In [10]:
data[:,1]

array([0.        , 0.01886709, 0.03772621, 0.05656938, 0.07538864,
       0.09417604, 0.11292363, 0.1316235 ])

---
### Writting a File

Simple writting of a file.

In [11]:
import numpy as np

# open the file for writting
outfile = open('out_file1.txt','w')

# writting a header
headerstring = '# This is the header for the file'
outfile.write(headerstring)

# write n lines of data
n = 100
for i in range(n):
    rand1 = np.random.random()
    rand2 = np.random.random()
    outstring = f'\n{rand1:.10f} , {rand2:.10f}'
    outfile.write(outstring)
    
# close the file
outfile.close()

---
#### Writting using `numpy`

Writting a file with 50 samples of random data

In [12]:
import numpy as np

data = np.random.random([50,2])

np.savetxt('out_file2.txt', data, fmt='%5.5f', header='This is the header of the file')

Writting with comma delimiters

In [13]:
import numpy as np

data = np.random.random([50,2])

np.savetxt('out_file3.txt', data, delimiter = ',', 
           fmt='%5.5f', header='This is the header of the file')