# Computational Astrophysics
## 01. Fundamentals of Python

---
## Eduard Larrañaga

Observatorio Astronómico Nacional\
Facultad de Ciencias\
Universidad Nacional de Colombia

---

### About this notebook

In this notebook we present some of the fundamentals of `python` coding.

---

### Hello World!

In [1]:
print('Hello World!')

Hello World!


---
### Importing Modules and Output Formatting

In [2]:
import math

x = math.pi
print(f'An approximate value of pi is {x:.5f}')

An approximate value of pi is 3.14159


In [3]:
print('An approximate value of pi is {:.5f}'.format(x))

An approximate value of pi is 3.14159


In [4]:
print('An approximate value of pi is %5.5f'%x)

An approximate value of pi is 3.14159


Note the output formatting expression

`%[width][.precision]type`

`[width]` : Total number of digits (including decimal point)\
`[.precision]` : Digits in the decimal part of the number

`type` : <br>
d (Integer)\
f (float)\
e (Scientific Notation)\
g (same as 'e' if exponent is greater than -4 or less than precision, or equal as 'f' otherwise)

<br>
Complete information about output formatting can be found at

https://docs.python.org/3/tutorial/inputoutput.html


---
### Simple functions

In [5]:
import math as m

x = m.pi / 2.0
math.sin(x)

1.0

In [6]:
m.cos(x)

6.123233995736766e-17

In [7]:
x = m.pi / 2
m.cos(x)

6.123233995736766e-17

In [8]:
a = 2.0
b = 3.0
c = a + b
c

5.0

In [9]:
a/b

0.6666666666666666

In [10]:
m.sqrt(5*c)

5.0

In [11]:
m.exp(10.)

22026.465794806718

In [12]:
m.log(22026.47)

10.000000190915461

---
### Defining and manipulaitng arrays with `numpy` 

1-dimensional arrays

In [13]:
import numpy as np

a = np.array([0., 2., 4., 6. ])
a

array([0., 2., 4., 6.])

In [14]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
c = np.zeros(10,float)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
d = np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
e = np.linspace(1., 20., 9)
e

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [18]:
f = np.random.random(10)
f

array([0.93333317, 0.61485282, 0.06322491, 0.32189287, 0.76274814,
       0.34713704, 0.84192047, 0.80461895, 0.11323291, 0.98669832])

n-dimensional arrays

In [19]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a[0]

array([1, 2, 3])

In [21]:
a[1]

array([4, 5, 6])

In [22]:
a[1,1]

5

In [23]:
a[1,:]

array([4, 5, 6])

In [24]:
a[:,1]

array([2, 5, 8])

In [25]:
a[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.array([np.arange(3),np.arange(3),np.arange(3)])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [27]:
np.zeros([3,3],float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.random.random([3,4])

array([[0.92762939, 0.01138482, 0.91745766, 0.69850864],
       [0.46015911, 0.39892251, 0.97028722, 0.56019818],
       [0.85551933, 0.69965246, 0.9589061 , 0.17917664]])

Attributes of an array

In [39]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.ndim(a)

2

In [32]:
a.shape

(3, 3)

In [33]:
a.max()

9

In [34]:
a.min()

1

In [35]:
a.sum()

45

In [36]:
a[0,:].sum()

6

In [37]:
a[:,1].sum()

15

In [38]:
a.mean()

5.0

---
### Simple Operations with Arrays

In [40]:
import numpy as np

a = np.random.random([3,3])
b = np.random.random([3,3])
a, b

(array([[0.59657574, 0.63349275, 0.96978111],
        [0.7115549 , 0.52238239, 0.4412829 ],
        [0.75612056, 0.39421301, 0.23502946]]),
 array([[0.76372595, 0.36222714, 0.10118363],
        [0.92273771, 0.31742312, 0.78424869],
        [0.51282667, 0.98893499, 0.5125915 ]]))

In [41]:
c = a + 2
c

array([[2.59657574, 2.63349275, 2.96978111],
       [2.7115549 , 2.52238239, 2.4412829 ],
       [2.75612056, 2.39421301, 2.23502946]])

In [42]:
d = a + b
d

array([[1.36030169, 0.99571988, 1.07096474],
       [1.63429261, 0.83980551, 1.22553159],
       [1.26894723, 1.383148  , 0.74762096]])

In [43]:
e = a * b   # Elementwise product
e

array([[0.45562037, 0.22946826, 0.09812597],
       [0.65657854, 0.16581625, 0.34607554],
       [0.38775879, 0.38985104, 0.1204741 ]])

In [44]:
f = a @ b   # matrix product
f

array([[1.53749764, 1.37623164, 1.05428111],
       [1.25175651, 0.85996084, 0.70787328],
       [1.06175348, 0.63144856, 0.50614216]])

In [45]:
f = a.dot(b) # matrix product (alternative)
f

array([[1.53749764, 1.37623164, 1.05428111],
       [1.25175651, 0.85996084, 0.70787328],
       [1.06175348, 0.63144856, 0.50614216]])

In [46]:
g = a / b
g

array([[0.7811385 , 1.74888264, 9.58436772],
       [0.77113452, 1.64569735, 0.56268236],
       [1.47441739, 0.39862379, 0.45851221]])

In [47]:
10*np.sin(c)

array([[5.18432552, 4.86518069, 1.70967497],
       [4.1690512 , 5.80392231, 6.44454568],
       [3.75996633, 6.79719136, 7.87389756]])

In [48]:
np.exp(d)

array([[3.89736893, 2.70667213, 2.91819345],
       [5.12583075, 2.31591651, 3.4059762 ],
       [3.55710576, 3.98743433, 2.11196957]])

In [49]:
np.log10(f)

array([[ 0.18681446,  0.13869154,  0.02295643],
       [ 0.09751986, -0.06552132, -0.15004448],
       [ 0.02602369, -0.19966202, -0.29572748]])

Changing the shape of an array

In [50]:
a = np.random.random([3,4])
a.shape

(3, 4)

In [51]:
a

array([[0.21842601, 0.07733834, 0.22712986, 0.18819743],
       [0.78077729, 0.62070362, 0.32665342, 0.85102505],
       [0.25571204, 0.57301675, 0.58774728, 0.84426742]])

In [52]:
a.T # Transpose 

array([[0.21842601, 0.78077729, 0.25571204],
       [0.07733834, 0.62070362, 0.57301675],
       [0.22712986, 0.32665342, 0.58774728],
       [0.18819743, 0.85102505, 0.84426742]])

In [53]:
a.T.shape

(4, 3)

In [54]:
a.ravel() #flattens the array

array([0.21842601, 0.07733834, 0.22712986, 0.18819743, 0.78077729,
       0.62070362, 0.32665342, 0.85102505, 0.25571204, 0.57301675,
       0.58774728, 0.84426742])

In [55]:
a.reshape(6,2)

array([[0.21842601, 0.07733834],
       [0.22712986, 0.18819743],
       [0.78077729, 0.62070362],
       [0.32665342, 0.85102505],
       [0.25571204, 0.57301675],
       [0.58774728, 0.84426742]])